# Modelling

## Package Loading

In [1]:
from pickle import dump, load
import os
from sklearn.dummy import DummyClassifier
from sklearn.model_selection import GridSearchCV, StratifiedKFold, cross_validate
from sklearn.metrics import recall_score, precision_score
from sklearn.ensemble import HistGradientBoostingClassifier
import skops.io as sio

## Data Loading

In [2]:
with open('data/feature_sel/X_train.pkl', 'rb') as file:
    X_train = load(file)

with open('data/feature_sel/y_train.pkl', 'rb') as file:
    y_train = load(file)

with open('data/feature_sel/X_test.pkl', 'rb') as file:
    X_test = load(file)

with open('data/feature_sel/y_test.pkl', 'rb') as file:
    y_test = load(file)

print(f"Training data, row: {len(X_train)}")
display(X_train.head())
display(y_train.head())
print(f"Test data, row: {len(X_test)}")
display(X_test.head())

Training data, row: 7223

      CreditScore  Geography  Gender  Age  Tenure    Balance  EstimatedSalary
8217          725        1.0     0.0   47       1  104887.43         86622.56
1664          479        1.0     0.0   30       7  143964.36         41879.99
3599          655        0.0     0.0   34       3       0.00        159638.77
5540          684        0.0     1.0   38       4       0.00         75609.84
0             844        0.0     1.0   18       2  160980.03        145936.28

8217    1
1664    0
3599    0
5540    0
0       0
Name: Exited, dtype: int64

Test data, row: 2500

      CreditScore  Geography  Gender  Age  Tenure    Balance  EstimatedSalary
2223          589        0.0     0.0   31      10  110635.32        148218.86
9735          516        2.0     0.0   65       9  102541.10        181490.42
57            582        0.0     1.0   20       4       0.00         55763.66
9243          604        0.0     0.0   56       0   62732.65        124954.56
3428          574        0.0     0.0   34       5  112324.45         17993.43

## Define CV

In [3]:
skf = StratifiedKFold(shuffle=True, random_state=42)
skf.split(X_train, y_train)

## Benchmark

Benchmark used here is dummy classifier, assuming all customers would churn.

In [4]:
dummy_mdl = DummyClassifier(strategy='constant',
                            constant=1)

dummy_score = cross_validate(dummy_mdl, X_train, y_train,
                             scoring=['recall', 'precision'],
                             cv=skf)

print(f"Dummy Recall each splits: {dummy_score['test_recall']}")
print(f"Dummy Precision each splits: {dummy_score['test_precision']}")

Dummy Recall each splits: [1. 1. 1. 1. 1.]
Dummy Precision each splits: [0.20207612 0.20207612 0.20207612 0.20221607 0.20221607]

Here we see that, despite "All Churn" benchmark have consistent perfect recall, they also have consistent bad precision. In other words, "All Churn" benchmark will accuse everyone to churn, bringing a lot of false alarm.

In this case, we still are going to optimize recall while also provide precision metric as reality check.

## Fit Model

In [5]:
main_clf = HistGradientBoostingClassifier(max_iter=1000,
                                          categorical_features=['Geography', 'Gender'],
                                          early_stopping=True, ## force early stopping
                                          random_state=42,
                                          class_weight='balanced') ## weighting the class due to imbalanced
                                                                   ## data

main_param = {'learning_rate': [0.01, 0.05, 0.1, 0.12, 0.2, 0.3],
              'max_leaf_nodes': [(2**i)-1 for i in range(2,8)]}

best_main = GridSearchCV(main_clf, main_param,
                         scoring=['recall', 'precision'], ## report both recall and precision
                         refit='recall', ## optimize recall
                         cv=skf)

best_main.fit(X_train, y_train) ## NOTE: this already count as model

print(f"Best Strategy: {best_main.best_params_}")
print(f"Best Recall (cv average): {best_main.best_score_}")

Best Strategy: {'learning_rate': 0.3, 'max_leaf_nodes': 7}
Best Recall (cv average): 0.6835616438356165

In [6]:
best_id = best_main.best_index_
all_recall = [float(best_main.cv_results_['split'+str(i)+'_test_recall'][best_id]) for i in range(0,5)]
all_presis = [float(best_main.cv_results_['split'+str(i)+'_test_precision'][best_id]) for i in range(0,5)]

print(f"Model Recall each splits: {all_recall}")
print(f"Model Precision each splits: {all_presis}")

Model Recall each splits: [0.678082191780822, 0.6712328767123288, 0.6712328767123288, 0.6917808219178082, 0.7054794520547946]
Model Precision each splits: [0.42217484008528783, 0.4224137931034483, 0.38132295719844356, 0.427061310782241, 0.4153225806451613]

Here, we found that 0.68 is the maximum average recall that we can reach, with recall at each CV spread between 0.67 to 0.70. Despite being "worse" than benchmark, we also found improvement on precision: jump from 0.2 on benchmark to at worst 0.38 by the model. Thus the model would raise less false alarms

## Evaluate Model

We already fit our model in the last section. Now we are going to evaluate the performance of our model on test data to see if our model can maintain it's recall while still yield better precision against "all churn".

In [7]:
mdl = best_main.best_estimator_ ## load best model from Tuning object

dummy_mdl.fit(X_train, y_train) ## fit dummy classifier again

dummy_pred = dummy_mdl.predict(X_test)
mdl_pred   = mdl.predict(X_test)

print(f"Dummy Recall on test: {recall_score(y_test, dummy_pred)}")
print(f"Model Recall on test: {recall_score(y_test, mdl_pred)}")
print(f"Dummy Precision on test: {precision_score(y_test, dummy_pred)}")
print(f"Model Precision on test: {precision_score(y_test, mdl_pred)}")

Dummy Recall on test: 1.0
Model Recall on test: 0.6660117878192534
Dummy Precision on test: 0.2036
Model Precision on test: 0.3928157589803013

Here we found that

* Model's recall on test is, unfortunately, worse than any of the cv split's recall
* However, model's precision on test is still better against all churn. Almost twice than all churn's precision on test.

Thus we conclude that the model is good enough against benchmark and have no to less performance fluctuation based on CV, thus the model is ready to serve.

## Save Model

In [8]:
display(mdl)

if not os.path.exists('data/modelling'):
    os.makedirs('data/modelling')

obj_skops = sio.dump(mdl, "data/modelling/model.skops")

HistGradientBoostingClassifier(categorical_features=['Geography', 'Gender'],
                               class_weight='balanced', early_stopping=True,
                               learning_rate=0.3, max_iter=1000,
                               max_leaf_nodes=7, random_state=42)